
configs:
  jrpcx_config:
    content: |
      service_name: blockchain-hyper
      chain_id: hyper
      rpc_listen: :9545
      forward_proxy: false
      internal_api_listen: :9268
      block_interval: 10
      enable_pprof: true

      #native_node_url: https://rpc.hyperliquid.xyz/evm
      native_node_url: http://localhost:8545
      official_node_url: https://rpc.hyperliquid.xyz/evm

      # observability configurations.
      observability:
        static_resource:
          chain_id: hyper
          node: hybrid-a1
          group: state
        log:
          enable: true
          endpoint: fluent-bit-tcp://prod-k8-jrpcx-fluent-bit-37e181d705609ecd.elb.ap-northeast-1.amazonaws.com:5170

      processor:
        rate_limiter:
          rpc_methods:
            eth_call: 1000
        observability_log:
          enable: true
          slow_threshold:
            default: 2000
            rpc_methods: {'eth_call': 1000}
        rpc_cache:
          enable: true
        method_name_checker:
          enable: false
          regexp:
          denied_regexp:

services:
  jrpcx:
    network_mode: host
    restart: unless-stopped
    stop_grace_period: 5m
    image: 294354037686.dkr.ecr.ap-northeast-1.amazonaws.com/jrpcx:v0.26.0
    configs:
      - source: jrpcx_config
        target: /app/config.yml
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: '4G'
    command: ["/app/jrpcx", "run", "-c", "/app/config.yml"]

  node:
    network_mode: host
    stop_grace_period: 5m
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: '24G'
    restart: unless-stopped
    build: .
    entrypoint: "/home/hluser/hl-visor"
    environment:
      - RUST_BACKTRACE=full
    command:
      - run-non-validator
      - --replica-cmds-style
      - recent-actions
      - --serve-eth-rpc
      - --serve-info
    ports:
      - 4001:4001
      - 4002:4002
      - 8545:3001
    volumes:
      - /data/hyper:/home/hluser/hl
      - ./override_gossip_config.json:/home/hluser/override_gossip_config.json

  pruner:
    network_mode: host
    restart: unless-stopped
    build: ./pruner
    volumes:
      - /data/hyper:/home/hluser/hl