networks:
  hyperliquid:
    ipam:
      driver: default
      config:
        - subnet: 10.17.89.0/24

configs:
  jrpcx_config:
    content: |
      service_name: blockchain-hyper
      chain_id: hyper
      rpc_listen: :9545
      internal_api_listen: :9268
      block_interval: 10
      enable_pprof: true

      native_node_url: http://node:3001/evm
      official_node_url: https://rpc.hyperliquid.xyz/evm

      hyperliquid_info_server:
        enabled: true
        listen: :9546
        native_url: http://172.21.54.1:8545/info
        official_url: https://api.hyperliquid.xyz/info

      # observability configurations.
      observability:
        static_resource:
          chain_id: hyper
        log:
          enable: true
          endpoint: fluent-bit-tcp://prod-k8-jrpcx-fluent-bit-37e181d705609ecd.elb.ap-northeast-1.amazonaws.com:5170

      processor:
        rate_limiter:
          rpc_methods:
            eth_call: 1000
        observability_log:
          enable: true
          slow_threshold:
            default: 2000
            rpc_methods: {'eth_call': 1000}
        rpc_cache:
          enable: true

services:
  jrpcx:
    networks:
      - hyperliquid
    restart: unless-stopped
    stop_grace_period: 5m
    image: 294354037686.dkr.ecr.ap-northeast-1.amazonaws.com/jrpcx:v0.26.2
    configs:
      - source: jrpcx_config
        target: /app/config.yml
    ports:
      - 9545:9545
      - 9546:9546
      - 9268:9268
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: '4G'
    command: ["/app/jrpcx", "run", "-c", "/app/config.yml"]

  node:
    networks:
      - hyperliquid
    stop_grace_period: 5m
    deploy:
      resources:
        limits:
          cpus: '16'
          memory: '120G'
    restart: unless-stopped
    build: .
    entrypoint: "/home/hluser/hl-visor"
    ports:
      - 8545:3001
      - 4001:4001
      - 4002:4002
    environment:
      - RUST_BACKTRACE=full
    command:
      - run-non-validator
      - --replica-cmds-style
      - recent-actions
      - --serve-eth-rpc
      - --serve-info
    volumes:
      - /data/hyper:/home/hluser/hl
      - ./override_gossip_config.json:/home/hluser/override_gossip_config.json

  pruner:
    networks:
      - hyperliquid
    restart: unless-stopped
    build: ./pruner
    volumes:
      - /data/hyper:/home/hluser/hl