name: "hyperliquid"

networks:
  hyperliquid:
    ipam:
      driver: default
      config:
        - subnet: 10.17.89.0/24

services:
  jrpcx:
    networks:
      - hyperliquid
    restart: unless-stopped
    stop_grace_period: 5m
    image: 294354037686.dkr.ecr.ap-northeast-1.amazonaws.com/jrpcx:v0.25.0
    ports:
      - 8695:9545
      - 9268:9268
    volumes:
      - ./jrpcx.yml:/app/config.yml
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: '4G'
    command: ["/app/jrpcx", "run", "-c", "/app/config.yml"]
  node:
    networks:
      - hyperliquid
    stop_grace_period: 5m
    deploy:
      resources:
        limits:
          cpus: '12'
          memory: '24G'
    restart: unless-stopped
    build: .
    entrypoint: "/home/hluser/hl-visor"
    environment:
      - RUST_BACKTRACE=full
    command:
      - run-non-validator
      - --replica-cmds-style
      - recent-actions
      - --serve-eth-rpc
      - --serve-info
    ports:
      - 4001:4001
      - 4002:4002
      - 8696:3001
    volumes:
      - /data/hyper:/home/hluser/hl
      - ./override_gossip_config.json:/home/hluser/override_gossip_config.json

  pruner:
    networks:
      - hyperliquid
    restart: unless-stopped
    build: ./pruner
    volumes:
      - /data/hyper:/home/hluser/hl