name: "hyperliquid"

networks:
  hyperevm-mainnet:
    ipam:
      driver: default
      config:
        - subnet: 10.17.89.0/24

services:
  node:
    networks:
      - hyperevm-mainnet
    stop_grace_period: 5m
    deploy:
      resources:
        limits:
          cpus: '12'
          memory: '24G'
    restart: unless-stopped
    build: .
    entrypoint: "/home/hluser/hl-visor"
    environment:
      - RUST_BACKTRACE=full
    command:
      - run-non-validator
      - --replica-cmds-style
      - recent-actions
      - --serve-eth-rpc
      - --serve-info
    ports:
      - 4001:4001
      - 4002:4002
      - 8695:3001
    volumes:
      - /data/hyper:/home/hluser/hl/data
      - ./override_gossip_config.json:/home/hluser/override_gossip_config.json

  pruner:
    networks:
      - hyperevm-mainnet
    restart: unless-stopped
    build: ./pruner
    volumes:
      - /data/hyper:/home/hluser/hl/data